In [1]:
import tensorflow as tf
import numpy as np

In [68]:
print("TF: ", tf.__version__, "\nNumpy: ", np.__version__)

TF:  1.1.0 
Numpy:  1.12.1


# Primitive Data Types
- DT_FLOAT	tf.float32	32 bits floating point.
- DT_DOUBLE	tf.float64	64 bits floating point.
- DT_INT8	tf.int8	8 bits signed integer.
- DT_INT16	tf.int16	16 bits signed integer.
- DT_INT32	tf.int32	32 bits signed integer.
- DT_INT64	tf.int64	64 bits signed integer.
- DT_UINT8	tf.uint8	8 bits unsigned integer.
- DT_UINT16	tf.uint16	16 bits unsigned integer.
- DT_STRING	tf.string	Variable length byte arrays. Each element of a Tensor is a byte array.
- DT_BOOL	tf.bool	Boolean.
- DT_COMPLEX64	tf.complex64	Complex number made of two 32 bits floating points: real and imaginary parts.
- DT_COMPLEX128	tf.complex128	Complex number made of two 64 bits floating points: real and imaginary parts.
- DT_QINT8	tf.qint8	8 bits signed integer used in quantized Ops.
- DT_QINT32	tf.qint32	32 bits signed integer used in quantized Ops.
- DT_QUINT8	tf.quint8	8 bits unsigned integer used in quantized Ops.

In [5]:
h = tf.constant("Hello ")
w = tf.constant("World")
hw = h + w
print("hw: ", hw)
with tf.Session() as session:
    ans = session.run(hw)
    print(ans)

hw:  Tensor("add_1:0", shape=(), dtype=string)
b'Hello World'


In [6]:
session = tf.Session()
session.run(hw)

b'Hello World'

In [7]:
a = tf.constant(5, name = "a")
b = tf.constant(4)
c = tf.constant(3)

d = tf.multiply(a, b)
e = tf.add(c, d)
f = tf.subtract(d, e)

print("f: ", session.run(f))
print(tf.Graph())
print(tf.get_default_graph())
print(f.graph)

f:  -3


In [8]:
a, b 
# The name of the Tensor object is simply the name of its corresponding operation 
# (concatenated with a colon), followed by the index of that tensor in the outputs of the 
# operation that produced it —it is possible to have more than one.
# Objects residing within the same graph cannot have the same name
# As a consequence, it will automatically add an underscore and a number to distinguish the two. 
# However, both objects can have the same name when they are associated with different graphs

(<tf.Tensor 'a:0' shape=() dtype=int32>,
 <tf.Tensor 'Const_4:0' shape=() dtype=int32>)

In [9]:
g1 = tf.get_default_graph()
g2 = tf.Graph()
print(g1 is tf.get_default_graph())
with g2.as_default():
    print(g1 is tf.get_default_graph(), g2 is tf.get_default_graph())
print(g1 is tf.get_default_graph())

True
False True
True


In [12]:
g1 = tf.Graph()
g2 = tf.Graph()
with g1.as_default():
    c1 = tf.constant(4.0)

with g2.as_default():
    c2 = tf.constant(2.0)

#c = c1 + c2
#session.run(c)

In [13]:
# Group variable with name scope
with tf.name_scope("3"):
    c1 = tf.constant(4.0)
c1
    

<tf.Tensor '3/Const:0' shape=() dtype=float32>

In [14]:
fetchers = [a, b, c, d, e, f]
session.run(fetchers)

[5, 4, 3, 20, 23, -3]

In [15]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])
c

<tf.Tensor 'Const_6:0' shape=(2, 3) dtype=int32>

In [16]:
c = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]))
c

<tf.Tensor 'Const_7:0' shape=(2, 3) dtype=int64>

In [19]:
c = tf.constant(4, dtype='float64')
c.dtype

tf.float64

### TensorFlow operation	Description
- tf.constant(value)	Creates a tensor populated with values of as specified by arguments “value”
- tf.fill(shape,value)	Creates a tensor of shape “shape" and fills it with “value" 
- tf.zeros(shape)	Returns a tensor of shape “shape” and all elements set to zero
- tf.zeros_like(tensor)	Returns a tensor of the same type and shape as “tensor" with all elements set to zero
- tf.ones(shape)	Returns a tensor of shape “shape" and all elements set to 1
- tf.ones_like(tensor)	Returns a tensor of the same type and shape as “tensor" with all elements set to 1

In [26]:
c = tf.ones((4, 3))
session.run(c)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [29]:
c = tf.fill((4, 3), 1)
session.run(c)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

# TensorFlow operation	

Description
- tf.random_normal(shape, mean, stddev)	Outputs random values from a normal distribution
- tf.truncated_normal(shape, mean, stddev)	Outputs random values from a truncated normal distribution (values whose  magnitude is more than 2 standard deviations from the mean are dropped and re-picked).
- tf.random_uniform(shape, minval, maxval)	Generated values from a uniform distribution in the range [minval, maxval)
- tf.random_shuffle(tensor)	Randomly shuffles a tensor along its first dimension
- tf.random_crop(tensor, shape)	Slices a shape “shape” portion out of “tensor" at a uniformly chosen offset
- tf.multinomial(logits, n_samples)	Draws samples from a multinomial distribution
- tf.random_gamma(shape,alpha,beta)	Draws “shape" samples from each of the given Gamma distribution(s)


In [77]:
c = tf.random_uniform((4, 3), seed=100)
session.run(c)

array([[ 0.96174979,  0.44918132,  0.51270759],
       [ 0.83489168,  0.54734325,  0.80996978],
       [ 0.71889913,  0.39656377,  0.95373368],
       [ 0.93378425,  0.04777336,  0.07103348]], dtype=float32)

In [72]:
c = tf.random_normal((4, 3), mean=0, stddev=0.3, seed=100)
session.run(c)

array([[ 0.02630099, -0.07955143, -0.298599  ],
       [ 0.17631671, -0.30626023,  0.12118966],
       [ 0.14748672, -0.19404596, -0.03731908],
       [ 0.08446319,  0.31936881,  0.66740936]], dtype=float32)

In [84]:
c = tf.linspace(0.2, 0.3, 5)
print(c.get_shape())
session.run(c)

(5,)


(array([ 0.2       ,  0.22500001,  0.25      ,  0.27500001,  0.30000001], dtype=float32),)

In [89]:
c = tf.range(0.4, 5.0, 0.25)
print(c.get_shape())
session.run(c)

(19,)


array([ 0.40000001,  0.64999998,  0.89999998,  1.14999998,  1.39999998,
        1.64999998,  1.89999998,  2.1500001 ,  2.4000001 ,  2.6500001 ,
        2.9000001 ,  3.1500001 ,  3.4000001 ,  3.6500001 ,  3.9000001 ,
        4.1500001 ,  4.4000001 ,  4.6500001 ,  4.9000001 ], dtype=float32)

In [127]:
X = tf.random_normal((5, 10), mean = 0.0, stddev = 1.0, seed = 0)
w = tf.random_normal((10, 1), mean = 0.0, stddev = 1.0, seed = 0)
b = tf.fill((5, 1), 1.0)
s = tf.sigmoid(tf.matmul(X, w) - b)
session.run(s)

array([[ 0.9999913 ],
       [ 0.14483425],
       [ 0.99418771],
       [ 0.55156505],
       [ 0.99135911]], dtype=float32)

TensorFlow operator	Shortcut	Description
- tf.add()	a + b	Add a and b, element-wise
- tf.mul()	a * b	Multiply a and b, element-wise
- tf.sub()	a - b	Subtract a from b, element-wise
- tf.div()	a / b	Will perform element-wise integer division when given an integer type tensor, and floatingpoint (“true”) division on floating point tensors
- tf.pow()	a ** b	The result of raising each element in a to its corresponding element b, element-wise
- tf.mod()	a % b	Element-wise modulo
- tf.logical_and()	a & b	Returns the truth table of a & b, element-wise. dtype must be tf.bool
- tf.greater()	a > b	Returns the truth table of a > b, element-wise
- tf.greater_equal()	a >= b	Returns the truth table of a >= b, element-wise
- tf.less_equal()	a <= b	Returns the truth table of a <= b , element-wise
- tf.less()	a < b	Returns the truth table of a < b, element-wise
- tf.neg()	-a	Returns the negative value of each element in a
- tf.logical_not()	~a	Returns the logical NOT of each element in a. Only compatible with Tensor objectswith dtype of - tf.bool
- tf.abs()	abs(a)	Returns the absolute value of each element in a
- tf.logical_or()	a | b	Returns the truth table of a | b, element-wise. dtype must be tf.bool

# Variable 

During the optimization process, tuning the weights of the model by iterative updates requires that their current state be maintained. For that purpose, TensorFlow uses special objects called “Variables”. Variables, unlike other Tensor objects that are “refilled” across calls to run(), can maintain a fixed state in the graph. Like other Tensors, Variables can be used as input for other operations in the graph.

Using Variables is done in two stages: (1) we call the tf.Variable() function in order to create a Variable, and define what value it will be initialized with and (2) we then have to explicitly perform an initialization operation by running the session with the tf.initialize_all_variables() method, which allocates the memory for the variable and sets the initial value as defined in (1).

Like with other Tensor objects, Variables are only computed when the model runs, as we can see in the following example:


In [139]:
c = tf.constant(15, name = "c")
x = tf.Variable(c * 5, name = "x")
init = tf.global_variables_initializer()
session.run(init)
session.run(x)

75

# Placeholder

TensorFlow has designated built-in structures for feeding input values. These structures are called placeholders. Placeholders can be thought of as empty variables that will be filled with data later on. We use them by first constructing our graph and only when it is executed feed them with the input data.

Placeholders have three arguments we are already familiarized with: dtype for the type of data that will be inserted to them and two optional arguments — shape and name. If a shape is not fed, then the placeholder can be fed with data of any size. This is also the same as placing ‘None’ for a shape. We can also place ‘None’ for specific dimensions we are not sure about their length —for example, it is very common to use only for the rows dimension of a matrix, corresponding to the number of samples, while having the length of the columns (features) fixed. We feed the input values when running the session, just after stating what outputs we want to evaluate.

Whenever we define a placeholder, we must feed it with some input values or else an exception will be thrown. The input data is given as a dictionary, where each key corresponds to a placeholder variable name, and the matching values are the data values given in the form of a list or a numpy array.


In [158]:
X_data = np.random.randn(5, 10)
w_data = np.random.randn(10, 1)

X = tf.placeholder("float32", shape=(5, 10))
w = tf.placeholder("float32", shape=(10, 1))
b = tf.fill((5, 1), - 1.0)
s = tf.sigmoid(tf.matmul(X, w) + b)

session.run(s, feed_dict={X: X_data, w: w_data})

array([[ 0.31824806],
       [ 0.45627081],
       [ 0.13931248],
       [ 0.01367185],
       [ 0.69908071]], dtype=float32)

In [176]:
r = tf.constant([3, 4, 5, 9, 11], dtype="float32")
mean = tf.reduce_mean(r)
session.run(mean)

6.4000001

In [28]:

def generate_data(n, d, w = None, intercept = None, seed = None):
    if seed is not None:
        np.random.seed(seed)
    X = np.random.rand(n, d)
    if w is None:
        w = np.random.random(d)
    if intercept is None:
        intercept = 0.15
    noise = np.random.randn(n) * 0.1
    y = np.dot(X, w.T) + intercept + noise
    return X, y, intercept, w

n, d = 2000, 3
X,y,i,w = generate_data(n, d)
print("X shape: ", X.shape, "y shape: ", y.shape, "i", i, "W: ", w)

X shape:  (2000, 3) y shape:  (2000,) i 0.15 W:  [ 0.93581325  0.42314648  0.14204597]


In [324]:
tf.matmul(tf.constant(X_data), tf.constant(w_real.reshape(-1, 1)))

<tf.Tensor 'MatMul_116:0' shape=(2000, 1) dtype=float64>

# Control Dependencies

In some cases, it may be wise to postpone the evaluation of an operation even though all the operations it depends on have been executed. For example, if it uses a lot of memory but its value is needed only much further in the graph, it would be best to evaluate it at the last moment to avoid needlessly occupying RAM that other operations may need. Another example is a set of operations that depend on data located outside of the device. If they all run at the same time, they may saturate the device’s communication bandwidth, and they will end up all waiting on I/O. Other operations that need to communicate data will also be blocked. It would be preferable to execute these communication-heavy operations sequentially, allowing the device to perform other operations in parallel.

To postpone evaluation of some nodes, a simple solution is to add control dependencies. For example, the following code tells TensorFlow to evaluate x and y only after a and b have been evaluated:

In [47]:
a = tf.constant(1.0)
b = a + 2.0

with tf.control_dependencies([a, b]):
    x = tf.constant(3.0)
    y = tf.constant(4.0)

z = x + y
session.run(z)

7.0

In [77]:
s = tf.reduce_mean(tf.constant([3.0, 4.0, 8.0, 10.0]))
session.run(s)

6.25

In [36]:
n, d = 2000000, 3
X_data, y_data,i,w = generate_data(n, d)
print("\nW: ", w, "i", i)

X = tf.placeholder("float32", shape=[None, d])
y_true = tf.placeholder("float32", shape = [None])
b = tf.Variable(tf.random_normal([1, 1]), dtype="float32")
w = tf.Variable(tf.random_normal([1, d]), dtype="float32")
y_pred = tf.matmul(w, tf.transpose(X)) + b

print("y_pred shape: ", y_pred.get_shape(), "y_true shape: ", y_true.get_shape())

loss = tf.reduce_mean(tf.square(y_true - y_pred))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.5)
train = optimizer.minimize(loss)

with tf.Session() as session:
    init = tf.global_variables_initializer()
    session.run(init)
    for step in range(300):
        session.run(train, {X: X_data, y_true: y_data})
        if step % 10 == 0:
            print(step, session.run([w, b]))


W:  [ 0.93046755  0.22401114  0.90232682] i 0.15
y_pred shape:  (1, ?) y_true shape:  (?,)
0 [array([[ 1.64163113,  2.01862812,  0.45267594]], dtype=float32), array([[ 1.77253425]], dtype=float32)]
10 [array([[ 0.9564029 ,  0.70228124,  0.44119522]], dtype=float32), array([[ 0.37290725]], dtype=float32)]
20 [array([[ 0.90726435,  0.38960314,  0.67474651]], dtype=float32), array([[ 0.21698859]], dtype=float32)]
30 [array([[ 0.91184527,  0.2841109 ,  0.79788804]], dtype=float32), array([[ 0.18504253]], dtype=float32)]
40 [array([[ 0.91827118,  0.24455938,  0.85403699]], dtype=float32), array([[ 0.17112584]], dtype=float32)]
50 [array([[ 0.92275876,  0.22984327,  0.8793776 ]], dtype=float32), array([[ 0.16303372]], dtype=float32)]
60 [array([[ 0.92566574,  0.22472996,  0.89102989]], dtype=float32), array([[ 0.1580648]], dtype=float32)]
70 [array([[ 0.92751437,  0.22322957,  0.89654613]], dtype=float32), array([[ 0.15498783]], dtype=float32)]
80 [array([[ 0.92868036,  0.22299731,  0.89925